import { Injectable } from '@nestjs/common';

/**
 * Human-readable hints for the TP `matchEvents[].matchEventType` codes that
 * are attributed to a player.
 *
 * This module's own hand-written table — not imported from, generated by, or
 * mechanically derived from packages/parse-tp's decoders, and deliberately not
 * shared with tools/review-match's equivalent table either. Both necessarily
 * describe the same real-world meanings, so the labels often agree; the
 * independence is about not sharing code. The label is a reading aid, never
 * the datum to trust — the numeric code is always shown alongside it.
 */
@Injectable()
export class TpPlayerEventLabelsService {
  private readonly labels = new Map<number, string>([
    [3, 'completion'],
    [4, 'touchdown'],
    [5, 'interception'],
    [6, 'casualty caused'],
    [7, 'MVP award'],
    [8, 'injury'],
    [25, 'deflection'],
    [31, 'foul'],
    [32, 'sent off'],
    [46, 'successful landing'],
  ]);

  /** `"<code> (<label>)"`, or just `"<code>"` when the code is unknown. */
  describe(code: number): string {
    const label = this.labels.get(code);
    return label === undefined ? String(code) : `${code} (${label})`;
  }
}
