import { Injectable } from '@nestjs/common';

/**
 * Human-readable hints for TP's numeric `matchEvents[].matchEventType` codes.
 *
 * This module's own hand-written table — not imported from, generated by, or
 * mechanically derived from `packages/parse-tp`'s decoders. Both tables
 * necessarily describe the same real-world meanings, so their labels often
 * agree; the independence is about not sharing code or being auto-derived
 * from the decoders, not about disagreeing with them. It cannot by itself
 * catch a decoder that's simply wrong about what a code means — the label
 * here is a reading aid, never the datum a reviewer should trust. The numeric
 * code is always shown alongside it precisely so a reviewer can check the
 * code (and, if needed, cross-reference TP's own UI or documentation)
 * without relying on this table's wording. Codes absent here are shown bare,
 * which is also the honest answer for structural/no-op rows (0, 1, 18, 19,
 * 27) the importer drops.
 */
@Injectable()
export class TpRawCodeLabelsService {
  private readonly labels = new Map<number, string>([
    [3, 'completion'],
    [4, 'touchdown'],
    [5, 'interception'],
    [6, 'casualty caused'],
    [7, 'MVP award'],
    [8, 'injury'],
    [10, 'weather'],
    [11, 'inducements roll'],
    [12, 'winnings'],
    [13, 'fan factor'],
    [14, 'expensive mistake'],
    [15, 'journeyman signing'],
    [20, 'concession'],
    [23, 'prayers to Nuffle'],
    [25, 'deflection'],
    [26, 'dedicated fans roll'],
    [31, 'foul'],
    [32, 'sent off'],
    [42, 'secret objective'],
    [46, 'successful landing'],
  ]);

  /** `"<code> (<label>)"`, or just `"<code>"` when the code is unknown. */
  describe(code: number): string {
    const label = this.labels.get(code);
    return label === undefined ? String(code) : `${code} (${label})`;
  }
}
