import { Injectable } from '@nestjs/common';

/**
 * Human-readable hints for the `extraData.weatherType` code on a TP code-10
 * (weather) event. A code is only unique *within* its
 * `extraData.weatherTable`: table `0` is the classic table — and what an
 * event carrying no table at all is treated as — while later tables (e.g.
 * `13`, first seen in Major Season 30) reuse the same numbers for entirely
 * different conditions. The lookup is therefore composite, and an unknown
 * table falls back to the bare code rather than to table `0`, which would
 * print a confidently wrong condition.
 *
 * This module's own hand-written table — not imported from, generated by, or
 * mechanically derived from `packages/parse-tp`'s `WeatherTypeService`. Both
 * tables necessarily describe the same real-world conditions, so their
 * labels often agree; the independence is about not sharing code or being
 * auto-derived from the decoder, not about disagreeing with it. It cannot by
 * itself catch a decoder that's simply wrong about what a code means — the
 * label here is a reading aid, never the datum a reviewer should trust. The
 * numeric code is always shown alongside it precisely so a reviewer can
 * cross-reference TP's own UI or documentation without relying on this
 * table's wording. Pairs absent here are shown bare.
 */
@Injectable()
export class TpRawWeatherLabelsService {
  private readonly labels = new Map<number, Map<number, string>>([
    [
      0,
      new Map<number, string>([
        [0, 'dungeon'],
        [10, 'sweltering heat'],
        [20, 'very sunny'],
        [30, 'nice'],
        [40, 'pouring rain'],
        [50, 'blizzard'],
        [100, 'morning dew'],
        [101, 'blossoming flowers'],
        [102, 'misty morning'],
        [103, 'high winds'],
        [104, 'perfect conditions'],
        [105, 'melting astrogranite'],
        [106, 'blinding rays'],
        [107, 'monsoon'],
        [108, 'leaf-strewn pitch'],
        [109, 'autumnal chill'],
        [110, 'strong winds'],
        [111, 'cold winds'],
        [112, 'freezing'],
        [113, 'heavy snow'],
      ]),
    ],
    [
      13,
      new Map<number, string>([
        [40, 'very sunny'],
        [104, 'perfect conditions'],
        [131, 'sweltering heat'],
        [132, 'pouring rain'],
        [133, 'blizzard'],
      ]),
    ],
  ]);

  /**
   * `"<code> (<label>)"`, or just `"<code>"` when the table/code pair is
   * unknown — consistent with `TpRawCodeLabelsService.describe`.
   */
  describe(table: number, code: number): string {
    const label = this.labels.get(table)?.get(code);
    return label === undefined ? String(code) : `${code} (${label})`;
  }
}
